// AUTO-GENERATED BY FREESAIL CLI - DO NOT EDIT
// Re-run `freesail prepare catalog` to regenerate this file.

import type { FreesailComponent } from '@freesail/lit';
import type { FunctionImplementation } from '@freesail/core';

export const includedComponents: Record<string, FreesailComponent> = {
};

export const includedFunctions: Record<string, FunctionImplementation> = {
};
