// AUTO-GENERATED BY FREESAIL CLI - DO NOT EDIT
// Re-run `freesail prepare catalog` to regenerate this file.

import { standardCatalogComponents, standardCatalogFunctions } from '@freesail/standard-catalog';

export const includedComponents = {
  Row: standardCatalogComponents['Row']!,
  Column: standardCatalogComponents['Column']!,
  Card: standardCatalogComponents['Card']!,
  Spacer: standardCatalogComponents['Spacer']!,
};

export const includedFunctions = {
  formatString: standardCatalogFunctions['formatString']!,
  formatDate: standardCatalogFunctions['formatDate']!,
  now: standardCatalogFunctions['now']!,
};
