// AUTO-GENERATED BY FREESAIL CLI - DO NOT EDIT
// Re-run `freesail prepare catalog` to regenerate this file.

import { standardCatalogFunctions } from '@freesail/standard-catalog';

export const includedComponents = {
};

export const includedFunctions = {
  formatString: standardCatalogFunctions['formatString']!,
};
